
   
services:
  openssh-server:
    build: ./openssh
    environment:
      - PUID=1000
      - PGID=1000
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=test
      - USER_NAME=test
    ports:
      - "${SSH_PORT-127.0.0.1:8022}:2222"
    volumes:
      - ./openssh/config:/custom-cont-init.d:ro
    restart: unless-stopped

  chall:
    build: .
    restart: unless-stopped
    init: true
  healthcheck:
    build: ./healthcheck
    ports:
      - "${HTTP_PORT-127.0.0.1:8080}:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
