services:
  web.ctf:
    build: ./web
    ports:
      - "${HTTP_PORT-127.0.0.1:8080}:80"
    restart: unless-stopped
    user: "1001:1001"
    cap_drop:
    - ALL
    security_opt:
    - no-new-privileges
    deploy:
      resources:
        limits:
          memory: 100M
